---
- name: Deploy and Configure Nested vESX VMs
  hosts: localhost
  gather_facts: False
  vars_files:
    - answerfile.yml
  tasks:
    - name: Deploy Nested vESXi VMs
      nestedESXi:
        vcenter: "{{ vcenter.ip }}"
        vmname: "{{ item.key }}"
        vcenter_user: "{{ vcenter.user }}"
        vcenter_passwd: "{{ vcenter.password }}" 
        cluster: "{{ item.value.cluster }}"
        datastore: "{{ vcenter.datastore }}"
        portgroup: "{{ item.value.portgroup }}"
        cpucount: "{{ item.value.cpu }}"
        memory: "{{ item.value.ram }}"
        hdd: "{{ item.value.hdd }}"
        isopath: "{{ item.value.isopath }}"
      with_dict: "{{ vESX }}"
      async: 7200
      poll: 0
      register: deployment
    - name: Wait 5 minutes before start checking wheter the hosts are ready
      pause: minutes=5
    - name: Result check for second deployment
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      with_items: "{{ deployment.results }}"
      retries: 100
  tags: nestedESX

