---
- name: Configure vESX
  hosts: localhost
  gather_facts: False
  vars_files:
    - answerfile.yml
  tasks:
    - name: Test Exec in a VM
      vmware_vm_shell:
        hostname: 10.29.14.165
        username: administrator@vsphere.local
        password: VMware1!
        datacenter: 'DBGDC1'
        validate_certs: false
        vm_id: YasenTest
        vm_username: root
        vm_password: VMware1!
        vm_shell: /bin/esxcli
        vm_shell_args: "system hostname set --fqdn=SecondTest.vmlab.com"
        vm_shell_env:
        - "PATH=/bin"
        - "VAR=test"
        vm_shell_cwd: "/tmp"

