---
- name: Create and connect VDS
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Create vMotion vmk1
      vmware_vmkernel:
        hostname: "{{ item.value.ip }}"
        username: "root"
        password: "VMware1!"
        vswitch_name: "vSwitch0"
        portgroup_name: "vmotion"
        vlan_id: "{{ vmotion_vlan }}"
        validate_certs: False
        ip_address: "{{ item.value.vmotion_ip }}"
        subnet_mask: "{{ vmotion_mask }}"
        enable_vmotion: True
      with_dict: "{{ vESX }}"
    - name: Create Distributed Switch
      vmware_dvswitch:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        datacenter_name: "{{ vcenter.datacenter }}"
        validate_certs: false
        switch_name: "ComputeEdgeVDS"
        mtu: 9000
        uplink_quantity: 2
        discovery_proto: lldp
        discovery_operation: both
        state: present
      register: vds
    - name: Create Management Portgroup
      vmware_dvs_portgroup:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        validate_certs: false
        portgroup_name: Management
        switch_name: "ComputeEdgeVDS"
        vlan_id: "{{ physicalESX.vlan }}"
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
      register: pg
    - name: Create vMotion Portgroup
      vmware_dvs_portgroup:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        validate_certs: false
        portgroup_name: vMotion
        switch_name: "ComputeEdgeVDS"
        vlan_id: "{{ vmotion_vlan }}"
        num_ports: 120
        portgroup_type: earlyBinding
        state: present
      register: vmotion_pg
    - name: Migrate uplink1 to the new VDS
      vmware_dvs_host:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.ip }}"
        switch_name: "ComputeEdgeVDS"
        vmnics:
          - vmnic1
        state: present
      with_dict: "{{ vESX }}"
      register: vmnic0res
    - name: Migrate vmk0 to the new VDS
      vmware_migrate_vmk:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.ip }}"
        device: vmk0
        current_switch_name: vSwitch0
        current_portgroup_name: "Management Network"
        migrate_switch_name: "ComputeEdgeVDS"
        migrate_portgroup_name: Management
      with_dict: "{{ vESX }}"
      register: vmkmigrate
    - name: Migrate vmk1 to the new VDS
      vmware_migrate_vmk:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.ip }}"
        device: vmk1
        current_switch_name: vSwitch0
        current_portgroup_name: "vmotion"
        migrate_switch_name: "ComputeEdgeVDS"
        migrate_portgroup_name: vMotion
      with_dict: "{{ vESX }}"
      register: vmkmigrate
    - name: Migrate second uplinks to the new VDS
      vmware_dvs_host:
        hostname: "{{ vcenter.ip }}"
        username: "{{ vcenter.user }}"
        password: "{{ vcenter.password }}"
        validate_certs: false
        esxi_hostname: "{{ item.value.ip }}"
        switch_name: "ComputeEdgeVDS"
        vmnics:
          - vmnic1
          - vmnic0
        state: present
      with_dict: "{{ vESX }}"
      register: vmnicsres
      ignore_errors: yes




